spring.application.name=react-flow-be
server.port=8085

# eureka.client.enabled=false
eureka.instance.prefer-ip-address=true
# eureka.instance.prefer-ip-address=false
# eureka.instance.hostname=host.docker.internal
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_HOST:localhost}:8761/eureka


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://mysql-diagram:3306/schema_visualizer?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false

# Logging Configuration
logging.level.com.example.react_flow_be=DEBUG
logging.level.com.example.react_flow_be.service=DEBUG
logging.level.com.example.react_flow_be.controller=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.messaging=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Connection pool settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# WebSocket Configuration
spring.websocket.sockjs.enabled=true
spring.websocket.sockjs.heartbeat-time=25000

spring.jackson.time-zone=Asia/Ho_Chi_Minh
