spring.application.name=account-service
server.port=8082

# Eureka
# eureka.client.enabled=false
eureka.instance.prefer-ip-address=true
# eureka.instance.prefer-ip-address=false
# eureka.instance.hostname=host.docker.internal
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_HOST:localhost}:8761/eureka

# Database - Development (Local PostgreSQL)
spring.datasource.url=jdbc:mysql://mysql-diagram:3306/schema_account?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Kafka - Development
# spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.example.accountservice.controller

# Logging
logging.level.com.example.accountservice=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Console output với ANSI colors
spring.output.ansi.enabled=ALWAYS

# JWT Configuration
jwt.secret=mySecretKeyForJwtTokenThatShouldBeAtLeast256BitsLongToEnsureSecurityAndProperFunctioning
jwt.expiration=86400000

#Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

#Actuator
management.endpoints.web.exposure.include=heapdump

accountservice.api-gateway-url=${API_GATEWAT_URL:http://localhost:8080}
accountservice.account-service-url=${ACCOUNT_SERVICE_URL:http://localhost:8082}

https.config=${HTTPS:false}

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# OAuth2 redirect URL
oauth2.redirect-uri=${OAUTH2_FRONTEND_REDIRECT:http://localhost:5173}
